linters:
  enable:
    - goimports
    - gofmt
    - golint
    - lll
    - whitespace
    - wsl
linters-settings:
  lll:
    line-length: 140
    tab-width: 4
output:
  format: colored-line-number
  print-issued-lines: false